import { EnginePreset } from './types';

export const ENGINE_PRESETS: EnginePreset[] = [
  {
    id: '2jz',
    name: 'Toyota 2JZ-GTE',
    badge: '3.0L Turbo I6',
    description: 'Legendary inline-6 twin-turbocharged iron-block engine with smooth 120° harmonic balance.',
    cylinders: 6,
    layout: 'I6',
    displacementLiters: 3.0,
    boreMm: 86.0,
    strokeMm: 86.0,
    rodLengthMm: 142.0,
    compressionRatio: 8.5,
    maxRpm: 8200,
    idleRpm: 750,
    firingOrder: [1, 5, 3, 6, 2, 4],
    cylinderPhases: [0, 120, 240, 360, 480, 600],
    soundTimbre: {
      roughness: 0.4,
      bassBoost: 1.4,
      highPitchGain: 1.2,
      pulseDistortion: 1.1,
    },
  },
  {
    id: 'ls454',
    name: 'Chevrolet 454 Big Block',
    badge: '7.4L V8 Crossplane',
    description: 'American pushrod V8 with signature crossplane idle lope and massive low-end torque.',
    cylinders: 8,
    layout: 'V8',
    displacementLiters: 7.4,
    boreMm: 107.9,
    strokeMm: 101.6,
    rodLengthMm: 155.7,
    compressionRatio: 10.2,
    maxRpm: 6500,
    idleRpm: 680,
    firingOrder: [1, 8, 7, 2, 6, 5, 4, 3],
    cylinderPhases: [0, 90, 180, 270, 360, 450, 540, 630],
    soundTimbre: {
      roughness: 1.6,
      bassBoost: 2.2,
      highPitchGain: 0.8,
      pulseDistortion: 1.5,
    },
  },
  {
    id: 'ej25',
    name: 'Subaru EJ25',
    badge: '2.5L Turbo Boxer-4',
    description: 'Horizontally opposed 4-cylinder engine with iconic unequal-length exhaust manifold rumble.',
    cylinders: 4,
    layout: 'Boxer4',
    displacementLiters: 2.5,
    boreMm: 99.5,
    strokeMm: 79.0,
    rodLengthMm: 130.5,
    compressionRatio: 8.2,
    maxRpm: 7200,
    idleRpm: 700,
    firingOrder: [1, 3, 2, 4],
    cylinderPhases: [0, 180, 360, 540],
    soundTimbre: {
      roughness: 1.2,
      bassBoost: 1.8,
      highPitchGain: 1.0,
      pulseDistortion: 1.3,
    },
  },
  {
    id: 'k20',
    name: 'Honda VTEC K20',
    badge: '2.0L DOHC i-VTEC I4',
    description: 'High-revving naturally aspirated screamer with dual cam profiles engaging at 5,800 RPM.',
    cylinders: 4,
    layout: 'I4',
    displacementLiters: 2.0,
    boreMm: 86.0,
    strokeMm: 86.0,
    rodLengthMm: 139.0,
    compressionRatio: 11.5,
    maxRpm: 9000,
    idleRpm: 850,
    firingOrder: [1, 3, 4, 2],
    cylinderPhases: [0, 180, 360, 540],
    soundTimbre: {
      roughness: 0.5,
      bassBoost: 0.9,
      highPitchGain: 1.8,
      pulseDistortion: 1.2,
    },
  },
  {
    id: 'audi_i5',
    name: 'Audi Quattro 2.2T',
    badge: '2.2L Turbo I5 Group B',
    description: 'Legendary 5-cylinder with uneven 144° firing interval that dominated Group B rallying.',
    cylinders: 5,
    layout: 'I5',
    displacementLiters: 2.2,
    boreMm: 81.0,
    strokeMm: 86.4,
    rodLengthMm: 144.0,
    compressionRatio: 9.3,
    maxRpm: 8000,
    idleRpm: 800,
    firingOrder: [1, 2, 4, 5, 3],
    cylinderPhases: [0, 144, 288, 432, 576],
    soundTimbre: {
      roughness: 0.9,
      bassBoost: 1.3,
      highPitchGain: 1.5,
      pulseDistortion: 1.4,
    },
  },
  {
    id: 'ferrari_f136',
    name: 'Ferrari F136',
    badge: '4.5L Flat-Plane V8',
    description: '180° flat-plane crankshaft Italian exotic with lightning fast throttle response and high pitch.',
    cylinders: 8,
    layout: 'V8',
    displacementLiters: 4.5,
    boreMm: 94.0,
    strokeMm: 81.0,
    rodLengthMm: 140.0,
    compressionRatio: 12.5,
    maxRpm: 9200,
    idleRpm: 1000,
    firingOrder: [1, 8, 3, 6, 4, 5, 2, 7],
    cylinderPhases: [0, 90, 180, 270, 360, 450, 540, 630],
    soundTimbre: {
      roughness: 0.3,
      bassBoost: 0.8,
      highPitchGain: 2.1,
      pulseDistortion: 1.3,
    },
  },
  {
    id: 'kohler',
    name: 'Kohler Command PRO',
    badge: '0.75L 90° V-Twin',
    description: 'Compact air-cooled utility engine with uneven firing pulse rhythm.',
    cylinders: 2,
    layout: 'V2',
    displacementLiters: 0.75,
    boreMm: 83.0,
    strokeMm: 69.0,
    rodLengthMm: 110.0,
    compressionRatio: 9.1,
    maxRpm: 4000,
    idleRpm: 1200,
    firingOrder: [1, 2],
    cylinderPhases: [0, 270],
    soundTimbre: {
      roughness: 1.8,
      bassBoost: 1.5,
      highPitchGain: 0.7,
      pulseDistortion: 1.6,
    },
  },
];
